Importar librerias

In [ ]:
import polars as pl
from datetime import datetime

# Frame de ejemplo

In [ ]:
lf = pl.LazyFrame({
    "Date": [
        datetime(2020, 1, 1),
        datetime(2020, 1, 2),
        datetime(2020, 1, 3),
        datetime(2020, 1, 4),
        datetime(2020, 1, 5),
        datetime(2020, 2, 6),
        datetime(2020, 2, 7),
        datetime(2020, 2, 8),
        datetime(2020, 2, 9),
        datetime(2020, 2, 10),
        datetime(2020, 3, 11),
        datetime(2020, 3, 12),
        datetime(2020, 3, 13),
        datetime(2020, 3, 14),
        datetime(2020, 3, 15),
        datetime(2020, 5, 16),
        datetime(2020, 5, 17),
        datetime(2020, 5, 18),
        datetime(2020, 5, 19),
        datetime(2020, 5, 20)
    ],
    "entry_time": [
        datetime(2020, 1, 1),
        datetime(2020, 1, 1),
        datetime(2020, 1, 1),
        datetime(2020, 1, 1),
        datetime(2020, 1, 1),
        datetime(2020, 2, 6),
        datetime(2020, 2, 6),
        datetime(2020, 2, 6),
        datetime(2020, 2, 6),
        datetime(2020, 2, 10),
        datetime(2020, 3, 10),
        datetime(2020, 3, 10),
        datetime(2020, 3, 10),
        datetime(2020, 3, 10),
        datetime(2020, 3, 10),
        datetime(2020, 5, 16),
        datetime(2020, 5, 16),
        datetime(2020, 5, 16),
        datetime(2020, 5, 16),
        datetime(2020, 5, 16)
    ],
    "High": [
        2110, 2120, 2130, 2140, 2150, 2160, 2170, 2180, 2190, 2200,
        2210, 2220, 2230, 2240, 2250, 2260, 2270, 2280, 2290, 2300
    ],
    "Low": [
        2105, 2115, 2125, 2135, 2145, 2155, 2165, 2175, 2185, 2195,
        2205, 2215, 2225, 2235, 2245, 2255, 2265, 2275, 2285, 2295
    ],
    "Highest": [
        2650, 2650, 2650, 2650, 2650, 2650, 2650, 2650, 2650, 2650,
        2650, 2650, 2650, 2650, 2650, 2650, 2650, 2650, 2650, 2650
    ],
    "Lowest": [
        2150, 2150, 2150, 2150, 2150, 2150, 2150, 2150, 2150, 2150,
        2150, 2150, 2150, 2150, 2150, 2150, 2150, 2150, 2150, 2150
    ]
})

Ver el lazyframe

In [ ]:
print(lf.collect())

shape: (20, 6)
┌─────────────────────┬─────────────────────┬──────┬──────┬─────────┬────────┐
│ Date                ┆ entry_time          ┆ High ┆ Low  ┆ Highest ┆ Lowest │
│ ---                 ┆ ---                 ┆ ---  ┆ ---  ┆ ---     ┆ ---    │
│ datetime[μs]        ┆ datetime[μs]        ┆ i64  ┆ i64  ┆ i64     ┆ i64    │
╞═════════════════════╪═════════════════════╪══════╪══════╪═════════╪════════╡
│ 2020-01-01 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2110 ┆ 2105 ┆ 2650    ┆ 2150   │
│ 2020-01-02 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2120 ┆ 2115 ┆ 2650    ┆ 2150   │
│ 2020-01-03 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2130 ┆ 2125 ┆ 2650    ┆ 2150   │
│ 2020-01-04 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2140 ┆ 2135 ┆ 2650    ┆ 2150   │
│ 2020-01-05 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2150 ┆ 2145 ┆ 2650    ┆ 2150   │
│ …                   ┆ …                   ┆ …    ┆ …    ┆ …       ┆ …      │
│ 2020-05-16 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2260 ┆ 2255 ┆ 2650    ┆ 2150   │
│ 2020-05-17 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2270 ┆ 2265 ┆ 2650    ┆ 2150   │
│ 2020-05-18 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2280 ┆ 2275 ┆ 2650    ┆ 2150   │
│ 2020-05-19 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2290 ┆ 2285 ┆ 2650    ┆ 2150   │
│ 2020-05-20 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2300 ┆ 2295 ┆ 2650    ┆ 2150   │
└─────────────────────┴─────────────────────┴──────┴──────┴─────────┴────────┘

Agrupar lazyframe

In [ ]:
lf_g = lf.group_by('entry_time').agg(
    pl.col('High').max().alias('max_value')
    ,pl.col('High').min().alias('min_value')
    ,pl.col('Highest').median().alias('max_high')
    ,pl.col('Lowest').mean().alias('min_low')
)
print(lf_g.collect())

shape: (5, 5)
┌─────────────────────┬───────────┬───────────┬──────────┬─────────┐
│ entry_time          ┆ max_value ┆ min_value ┆ max_high ┆ min_low │
│ ---                 ┆ ---       ┆ ---       ┆ ---      ┆ ---     │
│ datetime[μs]        ┆ i64       ┆ i64       ┆ f64      ┆ f64     │
╞═════════════════════╪═══════════╪═══════════╪══════════╪═════════╡
│ 2020-02-10 00:00:00 ┆ 2200      ┆ 2200      ┆ 2650.0   ┆ 2150.0  │
│ 2020-02-06 00:00:00 ┆ 2190      ┆ 2160      ┆ 2650.0   ┆ 2150.0  │
│ 2020-05-16 00:00:00 ┆ 2300      ┆ 2260      ┆ 2650.0   ┆ 2150.0  │
│ 2020-01-01 00:00:00 ┆ 2150      ┆ 2110      ┆ 2650.0   ┆ 2150.0  │
│ 2020-03-10 00:00:00 ┆ 2250      ┆ 2210      ┆ 2650.0   ┆ 2150.0  │
└─────────────────────┴───────────┴───────────┴──────────┴─────────┘

# **¿Qué es una Expresión en Polars?**

Una expresión en Polars es una operación o cálculo que se puede aplicar a una columna o conjunto de columnas. Las expresiones son como instrucciones, son los pasos a seguir que aùn no se concretaron, es como el plan antes de y es con el metodo `collect()` cuando se ejecuta el plan.

1. Características de las Expresiones:

* Encadenables: Puedes encadenar múltiples operaciones.

* Optimizables: Polars optimiza automáticamente las expresiones antes de ejecutarlas.

* Flexibles: Pueden usarse en casi cualquier contexto (selección, filtrado, agregación, etc.).

In [ ]:
import polars as pl

# Crear un DataFrame
df = pl.DataFrame({
    "nombre": ["Alice", "Bob", "Charlie"],
    "edad": [25, 30, 35]
})

# Usar expresiones para crear una nueva columna y filtrar
resultado = df.with_columns(
    (pl.col("edad") + 5).alias("edad_futura")  # Expresión 1: Suma 5 a "edad"
).filter(
    pl.col("edad_futura") > 30  # Expresión 2: Filtra por "edad_futura" > 30
)

print(resultado)

shape: (2, 3)
┌─────────┬──────┬─────────────┐
│ nombre  ┆ edad ┆ edad_futura │
│ ---     ┆ ---  ┆ ---         │
│ str     ┆ i64  ┆ i64         │
╞═════════╪══════╪═════════════╡
│ Bob     ┆ 30   ┆ 35          │
│ Charlie ┆ 35   ┆ 40          │
└─────────┴──────┴─────────────┘

# **¿Qué es `pl.col()`?**

`pl.col()` es una función que devuelve un objeto de tipo expresión en Polars. Una expresión es una representación de una operación que se aplicará a una columna o conjunto de columnas en un DataFrame o LazyFrame. Estas expresiones son lazy (perezosas), lo que significa que no se ejecutan inmediatamente, sino que se acumulan en un plan de ejecución que se evaluará más tarde (por ejemplo, al llamar a `.collect()` o `.agg()`).

¿Para qué se usa `pl.col()`?

* Seleccionar columnas: Hacer referencia a una columna por su nombre.

In [ ]:
# Selecciona la columna "edad"
pl.col("edad")

* Aplicar transformaciones: Realizar operaciones (matemáticas, de cadena, de fecha, etc.) sobre una columna.

In [ ]:
# Suma 10 a la columna "edad"
pl.col("edad") + 10

* Crear nuevas columnas: Definir cálculos que generen nuevas columnas.

In [ ]:
# Crea una nueva columna "edad_futura" que es "edad" + 10
df.with_columns(
    (pl.col("edad") + 10).alias("edad_futura")
)


* Filtrar datos: Usar expresiones en combinación con `.filter()`.

In [ ]:
# Filtra filas donde "edad" es mayor que 18
df.filter(pl.col("edad") > 18)

¿Cómo se diferencia `pl.col()` de otros métodos?

* Accede directamente a los datos de la columna (no es una expresión).

In [ ]:
df["columna"]

* Selecciona columnas, pero no devuelve una expresión (devuelve un DataFrame).

In [ ]:
df.select()

# I. CALCULOS AGRUPADOS

En Polars, hay tres maneras principales de realizar cálculos agrupados:

*   **`.group_by()`**
*   **`.over()`**
*   **`.group_by_dynamic()`**

En todos los metodos, se busca analizar de forma cuantitativa (metodos estadisticos y entre otros).

Veamos los siguientes ejemplos:

### 1. **group_by()**
*   Es un metodo de objetos de tipo LazyFrame y DataFrame. Es un metodo de agregación clásico, disponible también en sql.

Criterios de uso:

* Para crear tablas de resumen con estadísticas clave por categoría (grupo).
* Cuando queremos solo los calculos agrupados eliminando las demás filas (un nuevo frame con menos filas).
* Cuando trabajas con datasets muy grandes y necesitas reducir el volumen de datos desde el principio en el procesamiento.

¿como usarlo?:
1. Se debe especificar la columna donde están los grupos con `pl.col(...)`
2. Asignamos `True` al parámetro 'maintain_order'para mantener el orden de la columna de los grupos (es un paràmetro opcional).
2. Despues, se debe agregar el metodo `agg()` para los calculos agrupados
3. En caso de hacer varios calculos agregados, encerrar todo entre `[ ]` separando cada calculo por comas

* Cuando necesitas grupos definidos por combinaciones de varias columnas.

In [ ]:
# En este caso se agrupan por grupos encontrados en la columna *entry_time*
lf_group_by = lf.group_by("entry_time",maintain_order=True).agg(
    [pl.col("High").max().alias("max_agg"),
     pl.col("High").min().alias("min_agg"),]
)
print(lf_group_by.collect())

#
"""
Ejemplo de uso cuando queremos un resumen por cada grupo:

df.group_by("departamento").agg(
    pl.col("ventas").mean().alias("ventas_promedio"),
    pl.col("empleados").count().alias("total_empleados")
)

En este ejemplo tenemos una columna con todos los departamentos (grupos a analizar), el de ventas y el de empleados, y queremos obtener el promedio de ventas y el total de empleados por departamento.
----------------------------------------------------

Ejemplo de uso cuando necesitas grupos definidos por combinaciones de varias columnas.

df.group_by(["pais", "ciudad"]).agg(
    pl.col("ventas").sum().alias("ventas_totales")
)
------------------------------
Ejemplo de uso Para analizar distribuciones o frecuencias de categorías

df.group_by("estado_civil").agg(
    pl.col("edad").mean().alias("edad_promedio"),
    pl.col("id").count().alias("total_personas")
)

-------------------------
Ejemplo de uso Para Cuando necesitas filtrar grupos completos basados en una condición.

df.group_by("cliente").agg(
    pl.col("monto").sum().alias("total_gastado")
).filter(pl.col("total_gastado") > 1000)

otros ejemplos:

total_ventas = df.select(pl.col("ventas").sum()).item()
df.group_by("producto").agg(
    (pl.col("ventas").sum() / total_ventas).alias("porcentaje_global")
)

"""

shape: (5, 3)
┌─────────────────────┬─────────┬─────────┐
│ entry_time          ┆ max_agg ┆ min_agg │
│ ---                 ┆ ---     ┆ ---     │
│ datetime[μs]        ┆ i64     ┆ i64     │
╞═════════════════════╪═════════╪═════════╡
│ 2020-01-01 00:00:00 ┆ 2150    ┆ 2110    │
│ 2020-02-06 00:00:00 ┆ 2190    ┆ 2160    │
│ 2020-02-10 00:00:00 ┆ 2200    ┆ 2200    │
│ 2020-03-10 00:00:00 ┆ 2250    ┆ 2210    │
│ 2020-05-16 00:00:00 ┆ 2300    ┆ 2260    │
└─────────────────────┴─────────┴─────────┘

'\nEjemplo de uso cuando queremos un resumen por cada grupo:\n\ndf.group_by("departamento").agg(\n    pl.col("ventas").mean().alias("ventas_promedio"),\n    pl.col("empleados").count().alias("total_empleados")\n)\n\nEn este ejemplo tenemos una columna con todos los departamentos (grupos a analizar), el de ventas y el de empleados, y queremos obtener el promedio de ventas y el total de empleados por departamento.\n----------------------------------------------------\n\nEjemplo de uso cuando necesitas grupos definidos por combinaciones de varias columnas.\n\ndf.group_by(["pais", "ciudad"]).agg(\n    pl.col("ventas").sum().alias("ventas_totales")\n)\n------------------------------\nEjemplo de uso Para analizar distribuciones o frecuencias de categorías\n\ndf.group_by("estado_civil").agg(\n    pl.col("edad").mean().alias("edad_promedio"),\n    pl.col("id").count().alias("total_personas")\n)\n\n-------------------------\nEjemplo de uso Para Cuando necesitas filtrar grupos completos basados en una condición.\n\ndf.group_by("cliente").agg(\n    pl.col("monto").sum().alias("total_gastado")\n).filter(pl.col("total_gastado") > 1000)\n\notros ejemplos:\n\ntotal_ventas = df.select(pl.col("ventas").sum()).item()\ndf.group_by("producto").agg(\n    (pl.col("ventas").sum() / total_ventas).alias("porcentaje_global")\n)\n\n'

Recuerda que la forma de usar group_by es primero colocar el lazyframe o dataframe, luego colocar el metodo group_by, despues especificar el nombre de la columna donde estàn los grupos, luego colocar el metodo agg y dentro colocar los calculos agregados.

 2. **.over()**

*   Es una funcion de ventana (window functions). Disponible también en sql.

Criterios de uso:
*   Si solo necesitas añadir una columna con el maximo/minimo/promedio (cualquier calculo) de cada grupo.
*   Mantener las filas y agregar una nueva columna con la información adicional.
*   Ranking y Clasificación por Grupo.

¿como usarlo?:

*   Primero al lazy frame o data frame se agrega el metodo `with_columns()` para modificar las columnas del frame.
*   Se debe especificar la columna a modificar, puede ser con `pl.col(...)`
*   Se especifica el tipo de calculo a realizar 'max,min,mean' etc..
*   Se agrega el metodo `over()`
*   OPCIONAL: Se coloca un nombre para la colulmna con `alias()`, si no se modifica la columna a la que se hace referencia.

**ATENCIÓN: Cuando el rendimiento es crítico. .over() es menos eficiente que group_by.**
###### *(para obtener el mismo resultado que group_by se aplicaria el metodo `.unique()`.)*

En este caso se agrupan por grupos encontrados en la columna *entry_time*

In [ ]:
lf_over = lf.with_columns(
    pl.col("High").max().over("entry_time").alias("max_high")
)

print(lf_over.collect())

shape: (20, 7)
┌─────────────────────┬─────────────────────┬──────┬──────┬─────────┬────────┬──────────┐
│ Date                ┆ entry_time          ┆ High ┆ Low  ┆ Highest ┆ Lowest ┆ max_high │
│ ---                 ┆ ---                 ┆ ---  ┆ ---  ┆ ---     ┆ ---    ┆ ---      │
│ datetime[μs]        ┆ datetime[μs]        ┆ i64  ┆ i64  ┆ i64     ┆ i64    ┆ i64      │
╞═════════════════════╪═════════════════════╪══════╪══════╪═════════╪════════╪══════════╡
│ 2020-01-01 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2110 ┆ 2105 ┆ 2650    ┆ 2150   ┆ 2150     │
│ 2020-01-02 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2120 ┆ 2115 ┆ 2650    ┆ 2150   ┆ 2150     │
│ 2020-01-03 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2130 ┆ 2125 ┆ 2650    ┆ 2150   ┆ 2150     │
│ 2020-01-04 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2140 ┆ 2135 ┆ 2650    ┆ 2150   ┆ 2150     │
│ 2020-01-05 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2150 ┆ 2145 ┆ 2650    ┆ 2150   ┆ 2150     │
│ …                   ┆ …                   ┆ …    ┆ …    ┆ …       ┆ …      ┆ …        │
│ 2020-05-16 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2260 ┆ 2255 ┆ 2650    ┆ 2150   ┆ 2300     │
│ 2020-05-17 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2270 ┆ 2265 ┆ 2650    ┆ 2150   ┆ 2300     │
│ 2020-05-18 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2280 ┆ 2275 ┆ 2650    ┆ 2150   ┆ 2300     │
│ 2020-05-19 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2290 ┆ 2285 ┆ 2650    ┆ 2150   ┆ 2300     │
│ 2020-05-20 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2300 ┆ 2295 ┆ 2650    ┆ 2150   ┆ 2300     │
└─────────────────────┴─────────────────────┴──────┴──────┴─────────┴────────┴──────────┘

#¿Cual es la diferencia entre group_by y 'group_by_dynamic'?

La diferencia PRINCIPAL radica en el criterio de agrupación...

En el caso de `group_by` se agrupan por grupos donde dichos grupos son valores exactamente iguales (valores que se repiten) generando asi una lista por cada grupo (valores repetidos exactamente iguales) para despues calcular alguna metrica como el minimo, maximo etcc segun sea el caso.

**POR OTRO LADO**

En el caso de `group_by_dynamic` se agrupan por intervalos de tiempo, aqui no existe agrupación por valores repetidos como en el caso de `group_by`, aqui se agrupan los datos por caracteristicas propias del tiempo como las diferentes temporalidades (dia, hora, minuto, segundo), inicio en una hora o dia específico (por ejemplo iniciar la agrupación el martes), además tiene un argumento llamado group_by que es practicamente como usar la funcion en cuestión pero dentro de 'group_by_dynamic' (un combinao)

 3. **** → Agrupaciones temporales (series de tiempo).
Se usa cuando la columna de agrupación es una fecha.
Permite agrupar por intervalos como "1d", "1w", "1h", etc.


### 1. **.group_by_dynamic()**
*   Es un metodo de objetos de tipo LazyFrame y DataFrame. Está diseñado específicamente para agrupar datos de series temporales en ventanas dinámicas basadas en intervalos de tiempo (como días, horas, semanas, etc.).

Criterios de uso:

* Agrupación por intervalos de tiempo (ej: cada 1 hora, cada 5 días).
* Ventanas móviles superpuestas (ej: ventana de 7 días que se desplaza cada 3 días).
* Datos temporales con timestamps irregulares (ej: datos de sensores con mediciones no uniformes).
* Agregaciones en tiempo real (ej: calcular métricas cada 30 minutos).

¿como usarlo?:
1. Se debe especificar la columna donde están los grupos con `pl.col(...)`
2. Asignamos `True` al parámetro 'maintain_order'para mantener el orden de la columna de los grupos (es un paràmetro opcional).
2. Despues, se debe agregar el metodo `agg()` para los calculos agrupados
3. En caso de hacer varios calculos agregados, encerrar todo entre `[ ]` separando cada calculo por comas

In [ ]:
lf.group_by_dynamic("Date", every="5d").agg(
    pl.col("High").max()
)
lf.collect()

shape: (20, 6)
┌─────────────────────┬─────────────────────┬──────┬──────┬─────────┬────────┐
│ Date                ┆ entry_time          ┆ High ┆ Low  ┆ Highest ┆ Lowest │
│ ---                 ┆ ---                 ┆ ---  ┆ ---  ┆ ---     ┆ ---    │
│ datetime[μs]        ┆ datetime[μs]        ┆ i64  ┆ i64  ┆ i64     ┆ i64    │
╞═════════════════════╪═════════════════════╪══════╪══════╪═════════╪════════╡
│ 2020-01-01 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2110 ┆ 2105 ┆ 2650    ┆ 2150   │
│ 2020-01-02 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2120 ┆ 2115 ┆ 2650    ┆ 2150   │
│ 2020-01-03 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2130 ┆ 2125 ┆ 2650    ┆ 2150   │
│ 2020-01-04 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2140 ┆ 2135 ┆ 2650    ┆ 2150   │
│ 2020-01-05 00:00:00 ┆ 2020-01-01 00:00:00 ┆ 2150 ┆ 2145 ┆ 2650    ┆ 2150   │
│ …                   ┆ …                   ┆ …    ┆ …    ┆ …       ┆ …      │
│ 2020-05-16 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2260 ┆ 2255 ┆ 2650    ┆ 2150   │
│ 2020-05-17 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2270 ┆ 2265 ┆ 2650    ┆ 2150   │
│ 2020-05-18 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2280 ┆ 2275 ┆ 2650    ┆ 2150   │
│ 2020-05-19 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2290 ┆ 2285 ┆ 2650    ┆ 2150   │
│ 2020-05-20 00:00:00 ┆ 2020-05-16 00:00:00 ┆ 2300 ┆ 2295 ┆ 2650    ┆ 2150   │
└─────────────────────┴─────────────────────┴──────┴──────┴─────────┴────────┘

example

In [ ]:
import polars as pl
from datetime import datetime

# Crear DataFrame con timestamps
df = pl.DataFrame({
    "timestamp": pl.datetime_range(
        start=datetime(2023, 1, 1, 8),
        end=datetime(2023, 1, 1, 12),
        interval="30m",
        eager=True
    ),
    "value": [10, 20, 30, 40, 50, 60, 70, 80, 90],
    "category": ["A", "A", "B", "B", "A", "B", "A", "B", "A"]
})

print(df)

shape: (9, 3)
┌─────────────────────┬───────┬──────────┐
│ timestamp           ┆ value ┆ category │
│ ---                 ┆ ---   ┆ ---      │
│ datetime[μs]        ┆ i64   ┆ str      │
╞═════════════════════╪═══════╪══════════╡
│ 2023-01-01 08:00:00 ┆ 10    ┆ A        │
│ 2023-01-01 08:30:00 ┆ 20    ┆ A        │
│ 2023-01-01 09:00:00 ┆ 30    ┆ B        │
│ 2023-01-01 09:30:00 ┆ 40    ┆ B        │
│ 2023-01-01 10:00:00 ┆ 50    ┆ A        │
│ 2023-01-01 10:30:00 ┆ 60    ┆ B        │
│ 2023-01-01 11:00:00 ┆ 70    ┆ A        │
│ 2023-01-01 11:30:00 ┆ 80    ┆ B        │
│ 2023-01-01 12:00:00 ┆ 90    ┆ A        │
└─────────────────────┴───────┴──────────┘

* Ejemplo 1: Agrupación Diaria (ventanas de 1 día)

In [ ]:
result = df.group_by_dynamic(
    index_column="timestamp",
    every="1h",
    closed="both",  # Intervalo cerrado en ambos extremos (los incluye): [start, end]
    include_boundaries=True
).agg(pl.col("value").max())

print(result)

shape: (5, 4)
┌─────────────────────┬─────────────────────┬─────────────────────┬───────┐
│ _lower_boundary     ┆ _upper_boundary     ┆ timestamp           ┆ value │
│ ---                 ┆ ---                 ┆ ---                 ┆ ---   │
│ datetime[μs]        ┆ datetime[μs]        ┆ datetime[μs]        ┆ i64   │
╞═════════════════════╪═════════════════════╪═════════════════════╪═══════╡
│ 2023-01-01 08:00:00 ┆ 2023-01-01 09:00:00 ┆ 2023-01-01 08:00:00 ┆ 30    │
│ 2023-01-01 09:00:00 ┆ 2023-01-01 10:00:00 ┆ 2023-01-01 09:00:00 ┆ 50    │
│ 2023-01-01 10:00:00 ┆ 2023-01-01 11:00:00 ┆ 2023-01-01 10:00:00 ┆ 70    │
│ 2023-01-01 11:00:00 ┆ 2023-01-01 12:00:00 ┆ 2023-01-01 11:00:00 ┆ 90    │
│ 2023-01-01 12:00:00 ┆ 2023-01-01 13:00:00 ┆ 2023-01-01 12:00:00 ┆ 90    │
└─────────────────────┴─────────────────────┴─────────────────────┴───────┘

* Ejemplo 2: Ventanas Superpuestas (period > every)

In [ ]:
result = df.group_by_dynamic(
    index_column="timestamp",
    every="1h",
    period="2h",           # Ventanas de 2 horas
    closed="both",         # Intervalo cerrado en ambos extremos: [start, end]
    include_boundaries=True
).agg(pl.col("value").sum())

print(result)

shape: (5, 4)
┌─────────────────────┬─────────────────────┬─────────────────────┬───────┐
│ _lower_boundary     ┆ _upper_boundary     ┆ timestamp           ┆ value │
│ ---                 ┆ ---                 ┆ ---                 ┆ ---   │
│ datetime[μs]        ┆ datetime[μs]        ┆ datetime[μs]        ┆ i64   │
╞═════════════════════╪═════════════════════╪═════════════════════╪═══════╡
│ 2023-01-01 08:00:00 ┆ 2023-01-01 10:00:00 ┆ 2023-01-01 08:00:00 ┆ 150   │
│ 2023-01-01 09:00:00 ┆ 2023-01-01 11:00:00 ┆ 2023-01-01 09:00:00 ┆ 250   │
│ 2023-01-01 10:00:00 ┆ 2023-01-01 12:00:00 ┆ 2023-01-01 10:00:00 ┆ 350   │
│ 2023-01-01 11:00:00 ┆ 2023-01-01 13:00:00 ┆ 2023-01-01 11:00:00 ┆ 240   │
│ 2023-01-01 12:00:00 ┆ 2023-01-01 14:00:00 ┆ 2023-01-01 12:00:00 ┆ 90    │
└─────────────────────┴─────────────────────┴─────────────────────┴───────┘

Parámetros Clave de group_by_dynamic()


Parámetro	Descripción	Ejemplo
time_column	Columna de tipo datetime que se usará como referencia temporal.	"timestamp"
every	Duración entre el inicio de cada ventana (ej: "1h", "2d", "30m").	every="1d"
period	Duración de cada ventana (puede ser mayor que every para ventanas superpuestas).	period="2d"
offset	Desplazamiento inicial para ajustar el inicio de las ventanas.	offset="-1d"
truncate	Si True, trunca los resultados a las ventanas completas (útil para datos incompletos).	truncate=True
include_boundaries	Si True, incluye columnas con los límites de cada ventana.	include_boundaries=True

En Polars, el método **`.over()`** se usa en expresiones para calcular funciones de ventana (window functions), lo que permite mantener todas las filas en lugar de reducirlas como lo hace **`.group_by()`**.

Para obtener los mismos resultados de agregación usando **`.over()`** , podemos hacer lo siguiente:

In [ ]:
import polars as pl

print("Sales for each employee")
lf = pl.LazyFrame(
    {
        "Dia": [1, 1, 1, 2, 2, 2],
        "Sale": [10, 15, 16, 20, 30, 10],
        "Name": ["pepe", "carlos", "juan", "pepe", "carlos", "juan"],
    }
)

lf = lf.group_by(pl.col("Name"), maintain_order=True).agg(
    [
        pl.col("Sale").count().alias("count"),
        pl.col("Sale").first().alias("first"),
        pl.col("Sale").last().alias("last"),
        pl.col("Sale").max().alias("max"),
        pl.col("Sale").min().alias("min"),
        pl.col("Sale").arg_max().alias("arg_max"),
        pl.col("Sale").arg_min().alias("arg_min"),
        pl.col("Sale").sum().alias("sum"),
        pl.col("Sale").mean().alias("mean"),
        pl.col("Sale").median().alias("median"),
        pl.col("Sale").mode().alias("mode"),
        pl.col("Sale").std().alias("std"),
        pl.col("Sale").var().alias("var"),
        pl.col("Sale").quantile(0.8).alias("quantile"),
        pl.col("Sale").n_unique().alias("n_unique"),
        pl.col("Sale").kurtosis().alias("kurtosis"),
        pl.col("Sale").product().alias("product"),
        pl.col("Sale").skew().alias("skew"),
    ]
)

print(lf.collect())

Sales for each employee
shape: (3, 19)
┌────────┬───────┬───────┬──────┬───┬──────────┬──────────┬─────────┬──────┐
│ Name   ┆ count ┆ first ┆ last ┆ … ┆ n_unique ┆ kurtosis ┆ product ┆ skew │
│ ---    ┆ ---   ┆ ---   ┆ ---  ┆   ┆ ---      ┆ ---      ┆ ---     ┆ ---  │
│ str    ┆ u32   ┆ i64   ┆ i64  ┆   ┆ u32      ┆ f64      ┆ i64     ┆ f64  │
╞════════╪═══════╪═══════╪══════╪═══╪══════════╪══════════╪═════════╪══════╡
│ pepe   ┆ 2     ┆ 10    ┆ 20   ┆ … ┆ 2        ┆ -2.0     ┆ 200     ┆ 0.0  │
│ carlos ┆ 2     ┆ 15    ┆ 30   ┆ … ┆ 2        ┆ -2.0     ┆ 450     ┆ 0.0  │
│ juan   ┆ 2     ┆ 16    ┆ 10   ┆ … ┆ 2        ┆ -2.0     ┆ 160     ┆ 0.0  │
└────────┴───────┴───────┴──────┴───┴──────────┴──────────┴─────────┴──────┘